apiVersion: apps/v1
kind: Deployment
metadata:
  name: studytrack-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studytrack-frontend
  template:
    metadata:
      labels:
        app: studytrack-frontend
    spec:
      containers:
      - name: frontend
        image: fersc/studytrack-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: studytrack-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080